### PR TITLE
Update to nightly 2016-08-18

### PR DESCRIPTION
**Pull request by killercup**
with diesel_codegen 0.7.2 and dotenv macros 0.9.

### CODE REVIEW

**Comment by killercup** [comment]
I haven't gone through all of the guide, this is just the most basic stuff to get it working with the newer nightly.

**Comment by sgrif** [comment]
LGTM. Do you know how to deploy and have access to do so?

**Comment by killercup** [comment]
I still need to test/possibly update the section for working with syntex. I hope to have time for this later today, but no promises :)

I have middleman working locally and can create another PR targeting the gh-pages branch. I believe that is how currently do deployment, right? (Maybe I can also write a short .travis.yml that automatically triggers that for pushes to master).

**Comment by sgrif** [comment]
`bin/deploy` does what you need.

**Comment by killercup** [comment]
@sgrif, I added a bunch more stuff. Can you have a quick look at it? (If only to find all my many typos…)

- Update most version numbers
- Add cross links to 'Compiling for Stable Rust' section
- Add a new 'note' section style
- Add "A Note on Rust Nightly Versions"
- Add "A Note on Raw SQL in Migrations"
- Add "A Note on Syntex Versions"

Actually, let me just post this stuff as screenshots as it's probably easier for you.

diesel-guide-1

diesel-guide-2

diesel-guide-3

**Comment by sgrif** [comment]
LGTM

**Pull request merged**
