### PR TITLE
Migrate to mdBook

### LINKED ISSUE #118: Could we consider migrating to mdbook?
The website is built with middleman but its version is too old and we don't familiar with it. That makes it difficult to maintain (e.g. #106). Could we consider migrating to mdbook (or something else, which is easy to maintain) to make it easier?
cc @weiznich

### PR DESCRIPTION
**Pull request by JohnTitor**
Example: http://diesel.neet.club/

This should keep all the routes as requested on https://github.com/sgrif/diesel.rs-website/issues/118#issuecomment-800869071.

Closes #118, closes #106

### CODE REVIEW

**Comment by weiznich** [comment]
Thanks for working on this. I only had a quick look yet, as I'm quite busy with other tasks, so expect a more in depth review hopefully next week or so.
Thinks I've noticed so far:
* `mdbook` includes the ability to execute code in the playground. This is broken for our examples, we should probably fix it before releasing the rewrite
* The table of content on the left side could use some better structure. Something like grouping all guides below `Guides`.
* Maybe we should include some of the existing draft guides from the main diesel repo as well?
* At least I personally feel that we must restructure some content to fit the new design better. For example the "About diesel" page had expandable examples for the listed use cases. Now the expanding option is gone, which makes everything looking like quite a lot content. I do not really have a concrete idea here to fix that, it's just something I noticed while clicking through the pages.
* I don't know what customization mdbooks allow for the generated style, but if possible I would like to keep some of the design elements of the original page (something like color scheme, logo, …) If that's hard with mdbook we could also have a look at pandoc

**Comment by JohnTitor** [comment]
> * `mdbook` includes the ability to execute code in the playground. This is broken for our examples, we should probably fix it before releasing the rewrite

AFAIK we cannot include an external dep on the playground so I'm not sure how we fix it.


>  * Maybe we should include some of the existing draft guides from the main diesel repo as well?

Sounds good, I'm happy to do so.


>  * I don't know what customization mdbooks allow for the generated style, but if possible I would like to keep some of the design elements of the original page (something like color scheme, logo, …) If that's hard with mdbook we could also have a look at pandoc

I haven't checked deeply but I don't think the mdbook has much customizability. Uhm, or we can try to use the docusaurus, it should have more customizability.

**Comment by weiznich** [comment]
See #122 for an alternative version that preserves the exiting layout and style.

**Comment by weiznich** [comment]
Closed as we've gone for the pandoc version instead.

**Pull request closed without merging**
